name: sdk-antifraud-api
services:
  - name: sdk-antifraud-api
    type: web
    git:
      repository: https://github.com/luccastk/sdk-antifraud-api.git
      branch: main
    build:
      type: dockerfile
      dockerfile: Dockerfile
      context: .
    envs:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    ports:
      - port: 8080
        protocol: http
        http_path: /
    regions: [ fra, sin, iad, sfo ]
    instances:
      type: nano
      min_instances: 1
      max_instances: 3
    health_checks:
      http_path: /actuator/health
      initial_delay: 30
      period: 10
      timeout: 5
      success_threshold: 1
      failure_threshold: 3
